---
title: "3ratio_branch_model_analysis"
author: "LeAnn Ward"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

## Load Libraries ####
  library("readxl")
  library(ggplot2)
  library(reshape2)
  library(plyr)
  library(qvalue)
  library(tidyr)
  library(Rcpp)

```


```{r}
## Set Working Directory ####
  setwd("C:/Users/leann/OneDrive/grad research_newer/butterfly_aging/run7/branchmodel/")

## Set Variables ####
  speciesname1 = "Heliconius"
  speciesname2 = "PB"
  position = "clade"
  tl = "Density Distribution of Omega Estimates for Single-Copy Genes in the"
  title = paste(tl,speciesname1,"and",speciesname2,position,sep=" ")
  #Make the figure title
  
## Ctrl-F
  ## Replace 'Heliconius' 'Pieridae' or 'PB' with another group

## Open data file ####
  inFile = "edited_3rthp_branch_output.tsv"
  ld = read.delim(inFile, header = TRUE, sep = "\t")

  #Expected headers for BRANCH MODEL: Group \t Null.lnL \t Null.dN.dS \t Alt.lnL \t Alt.Omega.0.Background \t Alt.Omega.1
  
  
## Prepare input data ####
  
  #Calculate a log ratio column 
  #Formula: -2 * (Null.lnL - Alt.lnL)
  ld$LR <- -2 * (as.numeric(ld$Null.lnL) - as.numeric(ld$Alt.lnL))
  head(ld)
  
  
  #Change column names
  colnames(ld) <- c("Group", "nulllnl", "nullomega", "altlnl", "bg", "fg1","fg2", "LR")
  head(ld)
  
  print(nrow(ld[ld$fg1 > 99, ]))
  print(nrow(ld[ld$fg2 > 99, ]))
  print(nrow(ld[ld$bg > 99, ]))
  #ld <- ld[ld$fg1 < 99, ]
  nrow(ld)

## Find which rows are significant ####  
  #Calculate significance of the log ratio
  ld$pval <- pchisq(ld$LR, df = 1, lower.tail = FALSE)
  ld$padj <- p.adjust(ld$pval, method = 'fdr')
  
  head(ld)
  
  print("# of significant genes")
  nrow(subset(ld,pval<.05))
  
  print("# of genes with omega higher in Heliconius")
  nrow(subset(ld,fg1>bg))
  print("# of genes with omega higher in Pieridae")
  nrow(subset(ld,fg2>bg))
  
## Transform Data to be plotted ####
  sorted_ld = ld[order(-ld$LR),]
  head(sorted_ld)
  
  #Exclude omega values with subset() function
  wide_ld = subset(sorted_ld, select = c(Group,bg,fg1,fg2,LR,pval,padj))
  head(wide_ld)
  
  #Transform the previous data into long format so that "Background" and "Foreground" are categories
  #for each respective group
  
  long_ld = gather(wide_ld, level, omega, bg, fg1, fg2)
  head(long_ld)
  
  #rename bg and fg to "Background" and the foreground species
  long_ld$level <- replace(long_ld$level, long_ld$level=='bg', 'Background')
  long_ld$level <- replace(long_ld$level, long_ld$level=='fg1', speciesname1)
  long_ld$level <- replace(long_ld$level, long_ld$level=='fg2', speciesname2)
  head(long_ld)  
  
## bin the omegas ####
  #Set maximum values to consider
  c = 2
  long_ld$omega_bin <- long_ld$omega
  
  #any omega values that are greater than c should be set to c
  long_ld$omega_bin[long_ld$omega_bin > c] <- c
  head(long_ld)
  nrow(long_ld)
  
  nrow(long_ld[ , long_ld$omega_bin > 2])
  
## Graph the Results ####
  
  mu <- ddply(subset(long_ld), "level", summarise, grp.mean=mean(omega_bin))
  mu
  ?subset
  avg_bg = mu[1,2]
  favg_bg = format(round(avg_bg,2), nsmall=2)
  
  avg_fg1 = mu[2,2]
  favg_fg1 = format(round(avg_fg1,2), nsmall=2)
  
  avg_fg2 = mu[3,2]
  favg_fg2 = format(round(avg_fg2,2), nsmall=2)
  
  
  print(favg_bg)
  print(favg_fg1)
  print(favg_fg2)
  
  myplot <- ggplot(subset(long_ld, long_ld$omega_bin < 1.1), aes(x=omega_bin, fill = level, color=level)) +
    ggtitle(title) +
    geom_density(alpha = 0.6) +
    xlab('dN/dS') + 
    ylab('Density') +
    geom_vline(data=mu, aes(xintercept=grp.mean, color=level),
               linetype="dashed") +
    #geom_text(aes(x = .05, label = paste0("omega = ",favg_bg), y=10), colour = "red") +
    #geom_text(aes(x = .11, label = paste0("omega = ",favg_fg), y=8), colour = "blue") +
    scale_color_manual(values=c(Background="red", Heliconius="blueviolet",Pieridae="green")) +
    scale_fill_manual(values=c(Background="red", Heliconius="blueviolet",Pieridae="green")) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line =   element_line(colour = "black"))
  
  
  
  myplot

## Perform stats - Kolgomorov-Smirnoff test ####
  bg_omega = subset(long_ld, level == "Background")$omega_bin
  fg1_omega = subset(long_ld, level == "Heliconius")$omega_bin
  fg2_omega = subset(long_ld, level == "Pieridae")$omega_bin
  
  
  ks.test(fg1_omega, fg2_omega,bg_omega)
  ks.test(fg1_omega, fg2_omega)
  ks.test(fg1_omega, bg_omega)
  ks.test(fg2_omega, bg_omega)
  
    

```
